name: Identify and Remove Inactive Users

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  identify-inactive-users:
    name: Identify Inactive Users
    runs-on: ubuntu-latest
    steps:
      - name: Analyze User Activity
        id: analyze_user_activity
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
          organization: Virufy
          activity_days: 31

      - name: Save Report of Inactive Users
        run: |
          echo "Saving report of inactive users..."
          echo "${{ steps.analyze_user_activity.outputs.report_json }}" > inactive_users.json
          cat inactive_users.json

  remove-inactive-users:
    name: Remove Inactive Users
    needs: identify-inactive-users
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest GitHub CLI Release Info
        id: get_latest_gh_release
        run: |
          LATEST_RELEASE_INFO=$(curl -s https://api.github.com/repos/cli/cli/releases/latest)
          LATEST_TAG=$(echo "$LATEST_RELEASE_INFO" | jq -r '.tag_name')
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      
      - name: Download GitHub CLI
        run: |
          GH_VERSION=${{ env.LATEST_TAG }}
          GH_VERSION_NUMBER=$(echo $GH_VERSION | sed 's/^v//')
          GH_FILENAME="gh_${GH_VERSION_NUMBER}_linux_amd64.tar.gz"
          GH_DOWNLOAD_URL="https://github.com/cli/cli/releases/download/${GH_VERSION}/${GH_FILENAME}"
          echo "Downloading from: $GH_DOWNLOAD_URL"
          curl -fsSL "$GH_DOWNLOAD_URL" -o gh.tar.gz
          echo "GH_FILENAME=$GH_FILENAME" >> $GITHUB_ENV
      
      - name: Install GitHub CLI
        run: |
          tar -xzf gh.tar.gz
          sudo mv gh-*/bin/gh /usr/local/bin/
          rm -rf gh.tar.gz
          gh --version

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.ORGANIZATION_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Download Excluded Users List
        run: |
          curl -o excluded_users.txt https://raw.githubusercontent.com/virufy/org-auto/main/excluded_users.txt

      - name: Remove Users from Organization (Excluding Certain Users)
        run: |
          echo "Reading inactive users from report..."
          jq -r '.[] | select(.last_active_days > 31) | .login' inactive_users.json | while read -r user; do
            if grep -q "^$user$" excluded_users.txt; then
              echo "Skipping excluded user $user"
            else
              echo "Removing user $user from organization..."
              gh api -X DELETE orgs/Virufy/members/$user || echo "Failed to remove user $user"
              echo "Removed user $user successfully."
            fi
          done
